# Form implementation generated from reading ui file 'Data.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(880, 800)
        Dialog.setMinimumSize(QtCore.QSize(880, 800))
        Dialog.setMaximumSize(QtCore.QSize(880, 800))
        self.widget_2 = QtWidgets.QWidget(parent=Dialog)
        self.widget_2.setGeometry(QtCore.QRect(0, -10, 880, 800))
        self.widget_2.setMinimumSize(QtCore.QSize(880, 800))
        self.widget_2.setMaximumSize(QtCore.QSize(880, 800))
        self.widget_2.setSizeIncrement(QtCore.QSize(880, 800))
        self.widget_2.setStyleSheet("background: #1f8ddb")
        self.widget_2.setObjectName("widget_2")
        self.table_data = QtWidgets.QTableWidget(parent=self.widget_2)
        self.table_data.setGeometry(QtCore.QRect(20, 40, 821, 301))
        self.table_data.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(0)
        self.table_data.setRowCount(0)
        self.table = QtWidgets.QComboBox(parent=self.widget_2)
        self.table.setGeometry(QtCore.QRect(90, 360, 141, 21))
        self.table.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.table.setObjectName("table")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(30, 360, 51, 21))
        self.label_6.setObjectName("label_6")
        self.sql_ans = QtWidgets.QLineEdit(parent=self.widget_2)
        self.sql_ans.setGeometry(QtCore.QRect(10, 430, 841, 291))
        self.sql_ans.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.sql_ans.setObjectName("sql_ans")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(340, 400, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.sql_ans_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.sql_ans_button.setGeometry(QtCore.QRect(20, 730, 201, 41))
        self.sql_ans_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.sql_ans_button.setObjectName("sql_ans_button")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.clear_sql_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.clear_sql_button.setGeometry(QtCore.QRect(230, 730, 201, 41))
        self.clear_sql_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.clear_sql_button.setObjectName("clear_sql_button")
        self.change_table_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.change_table_button.setGeometry(QtCore.QRect(20, 390, 121, 31))
        self.change_table_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.change_table_button.setObjectName("change_table_button")
        self.add_data_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.add_data_button.setGeometry(QtCore.QRect(700, 350, 141, 31))
        self.add_data_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.add_data_button.setObjectName("add_data_button")
        self.save_table_data = QtWidgets.QPushButton(parent=self.widget_2)
        self.save_table_data.setGeometry(QtCore.QRect(700, 390, 141, 31))
        self.save_table_data.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.save_table_data.setObjectName("save_table_data")
        self.error_table_data = QtWidgets.QLabel(parent=self.widget_2)
        self.error_table_data.setGeometry(QtCore.QRect(330, 360, 361, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error_table_data.setFont(font)
        self.error_table_data.setStyleSheet("color: #f00")
        self.error_table_data.setObjectName("error_table_data")
        self.error_sql_ans = QtWidgets.QLabel(parent=self.widget_2)
        self.error_sql_ans.setGeometry(QtCore.QRect(470, 740, 361, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error_sql_ans.setFont(font)
        self.error_sql_ans.setStyleSheet("color: #f00")
        self.error_sql_ans.setObjectName("error_sql_ans")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Таблица:"))
        self.label_7.setText(_translate("Dialog", "SQL Запрос"))
        self.sql_ans_button.setText(_translate("Dialog", "Отправить"))
        self.label_8.setText(_translate("Dialog", "Данные таблицы"))
        self.clear_sql_button.setText(_translate("Dialog", "Очистить таблицу от запросов"))
        self.change_table_button.setText(_translate("Dialog", "выбрать"))
        self.add_data_button.setText(_translate("Dialog", "Добавить значения"))
        self.save_table_data.setText(_translate("Dialog", "Сохранить"))
        self.error_table_data.setText(_translate("Dialog", "Текст об ошибке"))
        self.error_sql_ans.setText(_translate("Dialog", "Текст об ошибке"))
